### ISSUE TITLE
routingControllersToSpec returning an indexing error

### ISSUE THREAD

**Issue by Downchuck** [epiphone/routing-controllers-openapi#18]
Seeing on the latest:
```
    TypeError: Cannot read property '0' of undefined

      at getParamSchema (node_modules/routing-controllers-openapi/src/generateSpec.ts:304:72)
      at tokens.filter.map (node_modules/routing-controllers-openapi/src/generateSpec.ts:128:28)
          at Array.map (<anonymous>)
      at getPathParams (node_modules/routing-controllers-openapi/src/generateSpec.ts:113:6)
      at getOperation (node_modules/routing-controllers-openapi/src/generateSpec.ts:36:10)
      at routes.map.route (node_modules/routing-controllers-openapi/src/generateSpec.ts:62:28)
          at Array.map (<anonymous>)
      at getPaths (node_modules/routing-controllers-openapi/src/generateSpec.ts:60:29)
      at Object.getSpec (node_modules/routing-controllers-openapi/src/generateSpec.ts:258:12)
      at Object.routingControllersToSpec (node_modules/routing-controllers-openapi/src/index.ts:28:16)
```

Note metadata is returning an object, and it does work with parseRoutes:

```
    MetadataArgsStorage {
      controllers:
       [ { type: 'json', target: [Function: UsersController], route: '/users' } ],
      middlewares: [],
      interceptors: [],
      uses: [],
      useInterceptors: [],
      actions:
       [ { type: 'get',
           target: [Function: UsersController],
           method: 'getUser',
           route: '/:userId' } ],
      params:
       [ { type: 'param',
           object: [UsersController],
           method: 'getUser',
           index: 0,
           name: 'userId',
           parse: false,
           required: true,
           classTransform: undefined } ],
      responseHandlers: [] }

  console.log index.ts:178
    [ { action:
         { type: 'get',
           target: [Function: UsersController],
           method: 'getUser',
           route: '/:userId' },
        controller:
         { type: 'json', target: [Function: UsersController], route: '/users' },
        options: {},
        params: [ [Object] ],
        responseHandlers: [] } ]
```

**Comment by Downchuck** [comment]
Neglected to add "emitDecoratorMetadata": true to my tsconfig.json
