### ISSUE TITLE
Error while genereting spec using routingControllersToSpec(storage, routingControllersOptions);

### ISSUE THREAD

**Issue by arthurvaverko** [epiphone/routing-controllers-openapi#26]
I getting this exception:

```
[2019-08-27T13:09:47.634] [ERROR] Server - Uncaught error: TypeError: Cannot read property '0' of undefined
    at getParamSchema (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:304:72)
    at tokens.filter.map (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:128:28)
    at Array.map (<anonymous>)
    at getPathParams (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:113:6)
    at getOperation (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:36:10)
    at routes.map.route (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:62:28)
    at Array.map (<anonymous>)
    at getPaths (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:60:29)
    at Object.getSpec (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\generateSpec.ts:258:12)
    at Object.routingControllersToSpec (C:\Code\skunk-budget\node_modules\routing-controllers-openapi\src\index.ts:28:16)
```

form the debug i figured that this method is the problem

```typescript
 @Get("/:id")
    @OnUndefined(404)
    getOne(@Param("id") id: number) {
        let users = [
            new User("James Coonce", "jcoonce", "james@none.com", 1),
            new User("Jim Coonce", "jimcoonce", "jim@none.com", 2),
            new User("Norman", "jcoonce", "norman@none.com", 3)
        ];

        let user = users.find(x => x.id === id);
        return user;
    }
```

the problem is within the call to `getPathParams(route)`

for some reason when the call goes to `getParamSchema(param)` specifically at
`const type = Reflect.getMetadata('design:paramtypes', object, method)[index];`
the result of Reflect.getMetadata('design:paramtypes', object, method) is undefined ..
i cant figure out what im missing .. 
anyone can help out ?

**Comment by epiphone** [comment]
Did you follow [these instructions](https://github.com/typestack/routing-controllers#installation) on setting up `routing-controllers`? Namely, importing `reflect-metadata` and setting the right Typescript config parameters.

**Comment by arthurvaverko** [comment]
thanks... was missing this in tsconfig
        "emitDecoratorMetadata": true,

**Comment by Jobayerdev** [comment]
![image](https://user-images.githubusercontent.com/34404032/120316752-92c89500-c2ff-11eb-9dd2-57d73192b8ec.png)
I am getting same Error
